name: Build Eleventy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies and build
      run: |
        npm install
        npm run build
    
    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: static-public
        path: public
